# Generated by Django 4.1.3 on 2023-02-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Tanıtım Başlık')),
                ('text', models.TextField(verbose_name='Ürün Tanıtım Açıklama')),
                ('image', models.FileField(upload_to='', verbose_name='Ürün Tanıtım Resmi')),
            ],
        ),
    ]
