# Generated by Django 4.1.3 on 2023-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapMy', '0002_satilikurun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('image', models.FileField(upload_to='', verbose_name='Logo')),
            ],
        ),
    ]
