# Generated by Django 4.1.3 on 2023-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapMy', '0004_alter_satilikurun_text_alter_urun_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='satilikurun',
            name='price',
            field=models.FloatField(null=True, verbose_name='Ürün Fiyatı'),
        ),
    ]
