# Generated by Django 4.1.3 on 2023-02-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aapMy', '0005_satilikurun_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Yorum yapan kişi')),
                ('text', models.TextField(verbose_name='yorum')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='yorum yapılan saat')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aapMy.satilikurun', verbose_name='Yorum yapılan ürün')),
            ],
        ),
    ]
